databases:
  - name: lady_DB
    databaseName: lady_DB
    user: lady
    region: singapore

services:
  - type: web
    name: lady_DB
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lady_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
